#!/usr/bin/env python3
"""
Generates SQL for fields.map_visibility based on outreach CSV + DB-native data quality.

Two strategies:
  1. NAMED venues  — specific facility names from CSV → matched by name in DB.
  2. GENERIC names — "Boisko — X", "Boisko sportowe", "Hala Sportowa" etc.
                    → visibility decided from DB-own columns (address / phone / email / website).

Usage:
  python3 scripts/set_map_visibility.py > scripts/set_map_visibility.sql
  Then paste into Supabase Dashboard → SQL Editor.

Visibility values (migration 024):
  'public'         — public map + event creation picker
  'organizer_only' — event creation only (no public map)
  'hidden'         — nowhere (junk / no data)
"""

import csv
import re
import sys

CSV_PATH = "scripts/obiekty_outreach.csv"

# ──────────────────────────────────────────────
# Names that are too generic to match individually
# (handled via DB-native column conditions instead)
# ──────────────────────────────────────────────
GENERIC_PREFIXES = (
    "boisko —",
    "boisko sportowe",
    "boisko sportowe ·",
    "boisko grunwald",   # ambiguous playarena aggregator
    "hala sportowa,",    # trailing comma = unnamed record
)

DEAD_DOMAINS = ("orlik2012.pl",)

NOISE_CITIES = {"poznań", "poznan", ""}


def q(s: str) -> str:
    return s.replace("'", "''")


def is_generic_name(name: str) -> bool:
    n = name.strip().lower()
    return any(n.startswith(p) for p in GENERIC_PREFIXES)


def is_specific_address(addr: str) -> bool:
    a = addr.strip().lower()
    if a in NOISE_CITIES:
        return False
    return bool(re.search(r'\d', a))


def has_contact(phone: str, email: str, www: str) -> bool:
    if phone.strip() or email.strip():
        return True
    w = www.strip().lower()
    if not w:
        return False
    return not any(d in w for d in DEAD_DOMAINS)


def classify_named_venue(rows: list[dict]) -> str:
    """
    Pick best visibility for a named venue from all its CSV rows.
    public > organizer_only > hidden
    """
    PRIO = {"public": 0, "organizer_only": 1, "hidden": 2}
    best = "hidden"

    for row in rows:
        addr  = row.get("Adres", "")
        phone = row.get("Telefon", "")
        email = row.get("E-mail", "")
        www   = row.get("WWW", "")

        specific = is_specific_address(addr)
        contact  = has_contact(phone, email, www)

        if specific and contact:
            vis = "public"
        elif specific or contact:
            vis = "public"   # named venue with ANY data → public
        else:
            vis = "organizer_only"

        if PRIO[vis] < PRIO[best]:
            best = vis

    return best


def main():
    try:
        fh = open(CSV_PATH, encoding="utf-8-sig")
    except FileNotFoundError:
        print(f"-- ERROR: CSV not found at {CSV_PATH}", file=sys.stderr)
        sys.exit(1)

    rows = list(csv.DictReader(fh))
    fh.close()

    # ── Group rows by Nazwa ─────────────────────────────────────────
    from collections import defaultdict
    by_name: dict[str, list[dict]] = defaultdict(list)
    for row in rows:
        name = row.get("Nazwa", "").strip()
        if name:
            by_name[name].append(row)

    # Split: named vs generic
    named_vis: dict[str, str] = {}   # name → visibility
    generic_names: list[str] = []

    for name, name_rows in by_name.items():
        if is_generic_name(name):
            generic_names.append(name)
        else:
            named_vis[name] = classify_named_venue(name_rows)

    # ── Stats ───────────────────────────────────────────────────────
    from collections import Counter
    named_counts = Counter(named_vis.values())

    print("-- ============================================================")
    print("-- set_map_visibility.sql")
    print("-- Generated by scripts/set_map_visibility.py — do NOT hand-edit.")
    print("--")
    print("-- Named venues:")
    print(f"--   public:         {named_counts['public']}")
    print(f"--   organizer_only: {named_counts['organizer_only']}")
    print(f"--   (generic names handled by separate DB-native block below)")
    print("-- ============================================================")
    print()

    # ── Block 1: Named venues — matched by name ─────────────────────
    print("-- ────────────────────────────────────────────────────────────")
    print("-- BLOCK 1: Named venues (matched by name)")
    print("-- ────────────────────────────────────────────────────────────")
    print()

    for target_vis in ("public", "organizer_only"):
        label = "PUBLIC" if target_vis == "public" else "ORGANIZER ONLY"
        names = sorted(n for n, v in named_vis.items() if v == target_vis)
        if not names:
            continue
        print(f"-- {label} — {len(names)} named venues")
        # Batch 40 per UPDATE for readability
        for i in range(0, len(names), 40):
            batch = names[i:i+40]
            in_list = ",\n          ".join(f"'{q(n)}'" for n in batch)
            print(f"UPDATE fields SET map_visibility = '{target_vis}'")
            print(f"  WHERE name IN ({in_list});")
            print()

    # ── Block 2: Generic names — visibility from DB-own columns ─────
    print("-- ────────────────────────────────────────────────────────────")
    print("-- BLOCK 2: Generic / ambiguous names — decided by DB data quality")
    print("--   Matches rows whose name starts with common prefixes.")
    print("--   Visibility is based on DB columns: address / phone / email / website.")
    print("-- ────────────────────────────────────────────────────────────")
    print()

    # Build ILIKE conditions for the generic name prefixes we saw
    # Use the actual names found in CSV; fall back to prefix ILIKE for safety
    generic_in = ", ".join(f"'{q(n)}'" for n in sorted(generic_names))

    print("-- Generic names in CSV (used for WHERE name IN below):")
    # Print as a comment list
    for n in sorted(generic_names):
        print(f"--   {n}")
    print()

    print("-- Mark as 'public' when DB record has both a proper address AND contact info")
    print("""UPDATE fields SET map_visibility = 'public'
  WHERE name IN (""" + generic_in + """)
  AND address IS NOT NULL
  AND address !~ '^\\s*(Pozna[nń])?\\s*$'   -- not blank / city-only
  AND position(',' IN address) > 0            -- contains comma = street+number
  AND (
    phone IS NOT NULL
    OR email IS NOT NULL
    OR (website IS NOT NULL AND website NOT LIKE '%orlik2012%')
  );
""")

    print("-- Mark as 'organizer_only' when there is contact but no specific address")
    print("""UPDATE fields SET map_visibility = 'organizer_only'
  WHERE name IN (""" + generic_in + """)
  AND map_visibility <> 'public'               -- don't downgrade what we just promoted
  AND (
    phone IS NOT NULL
    OR email IS NOT NULL
    OR (website IS NOT NULL AND website NOT LIKE '%orlik2012%')
  );
""")

    print("-- Mark remaining generic entries as 'hidden' (no address, no contact)")
    print("""UPDATE fields SET map_visibility = 'hidden'
  WHERE name IN (""" + generic_in + """)
  AND map_visibility NOT IN ('public', 'organizer_only');
""")

    print("-- ────────────────────────────────────────────────────────────")
    print("-- BLOCK 3: Safety net — hide anything still defaulting to")
    print("--           organizer_only with absolutely no contact data")
    print("-- ────────────────────────────────────────────────────────────")
    print()
    print("""UPDATE fields SET map_visibility = 'hidden'
  WHERE map_visibility = 'organizer_only'
  AND phone IS NULL
  AND email IS NULL
  AND website IS NULL;
""")

    print("-- Done. Review before running on production.")
    print(f"-- Total named venues processed: {len(named_vis)}")
    print(f"-- Total generic name groups: {len(generic_names)}")


if __name__ == "__main__":
    main()
