-- ============================================================
-- set_map_visibility.sql
-- Generated by scripts/set_map_visibility.py — do NOT hand-edit.
--
-- Named venues:
--   public:         98
--   organizer_only: 43
--   (generic names handled by separate DB-native block below)
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- BLOCK 1: Named venues (matched by name)
-- ────────────────────────────────────────────────────────────

-- PUBLIC — 98 named venues
UPDATE fields SET map_visibility = 'public'
  WHERE name IN ('12ft',
          'AKWEN',
          'AWF Poznań',
          'AZS Poznań',
          'Arena',
          'Atlantis Fitness Club',
          'Black Ball Klub bilardowy',
          'Boisko Orlik Jeżyce',
          'Boisko Os. Winogrady',
          'Boisko Park Sołacki',
          'Boisko Przepadek',
          'Boisko do piłki nożnej',
          'CITYZEN',
          'CITYZEN_',
          'Centrum Kultury Fizycznej. Uniwersytet Przyrodniczy w Poznaniu',
          'Centrum Sportowe UM',
          'Centrum Sportu Politechniki Poznańskiej: Hala Sportowa im. Wojciecha Weissa',
          'Centrum Sportu i Rekreacji Stadion Średzki',
          'Centrum Treningowe Polonii Środa Wielkopolska',
          'Concordia',
          'Cooliozum',
          'Dawny stadion Energetyka Poznań',
          'Fabryka Formy Bałtyk',
          'Fabryka Formy Korty Arena',
          'Fitness Klub CityFit - Siłownia 24h Poznań Galeria Pestka - HYROX TRAINING CLUB',
          'Fitness Point',
          'GOS Hala Sportowa',
          'GOSiR Komorniki',
          'Hala Dydaktyczno-Sportowa AWF',
          'Hala POSiR Sporty Walki',
          'Hala Sportowa',
          'Hala Sportowa AWF Poznań',
          'Hala Sportowa LO Św. Marii Magdaleny w Poznaniu',
          'Hala Sportowa Politechniki Poznańskiej',
          'Hala Sportowa Wydziału Kadr i Szkolenia KWP w Poznaniu',
          'Hala Sportowa w Czerwonaku',
          'Hala Sportowa w Tulcach',
          'Hala Uniwersytecka',
          'Hala Uniwersytetu Przyrodniczego',
          'Hala Widowiskowo-Sportowa');

UPDATE fields SET map_visibility = 'public'
  WHERE name IN ('Hala sportowa',
          'Hala sportowa Akademickiego Związeku Sportowego',
          'Hala sportowa Uniwersytetu Ekonomicznego',
          'Hala sportowo-widowiskowa Wacław',
          'Hangar',
          'KS Pocztowiec',
          'KS Warta Poznań',
          'Klub Uczelniany AZS Politechniki Poznańskiej',
          'Klub sportowy KS 1920 Mosina',
          'Kohorta',
          'Kompleks sportowo-rekreacyjny w Czerwonaku',
          'Kompleks sportowy w Owińskach',
          'Korty Rataje POSiR',
          'Korty Tenisowe AKT Poznań',
          'Korty tenisowe w Szreniawie GOSiR Komorniki',
          'Kórnickie Centrum Rekreacji i Sportu "OAZA"',
          'Kórnickie Centrum Rekreacji i Sportu OAZA',
          'LOSiR Hala widowiskowo - sportowa',
          'MK Bowling Poznań',
          'Młodzieżowy Ośrodek Sportowy',
          'Orlik',
          'Orlik - Os. Oświecenia',
          'Orlik 2012',
          'Orlik Rataje',
          'Orlik Wilda',
          'Ośrodek Przywodny Rataje',
          'Ośrodek Sportu i Rekreacji Tarnowo Podgórne',
          'Ośrodek Sportu i Rekreacji w Baranowie',
          'Ośrodek Sportu i Rekreacji w Opalenicy',
          'POSiR',
          'POSiR - Hala B',
          'Park Tenisowy Olimpia',
          'Park rekreacyjno-sportowy "FairPlayce"',
          'Parking Orlik Poznań 44',
          'Plek Centrum Sportu',
          'Poznańskie Ośrodki Sportu i Rekreacji - Hala A',
          'Poznańskie Ośrodki Sportu i Rekreacji - Hala C',
          'Poznańskie Ośrodki Sportu i Rekreacji POSiR',
          'Poznańskie Ośrodki Sportu i Rekreacji, Oddział Golęcin',
          'Poznańskie Ośrodki Sportu i Rekreacji, Oddział Malta');

UPDATE fields SET map_visibility = 'public'
  WHERE name IN ('Przystań KS Posnania',
          'Radojewko - Fabryka Dobrej Zabawy',
          'Red Oak',
          'Sport Club Poznań',
          'Stadion KKS Lechia Kostrzyn',
          'Stadion Lekkoatletyczny POSiR Golęcin',
          'Stadion OSiR w Mosinie',
          'Stadion POSiR Harcerska',
          'Stadion Sportowy GOSiR w Komornikach',
          'Strefa Sportu Tenis & Fitness',
          'Tenis Park Luboń',
          'Termy Maltańskie — Boiska',
          'WKS Grunwald Poznań - sekcja zapaśnicza',
          'Warta Poznań SA',
          'Wielkopolska Przychodnia Sportowo–Lekarska',
          'Xtreme Fitness Poznań Stary Browar',
          'Zespół Szkół Mistrzostwa Sportowego nr 2',
          'fairPlayce');

-- ORGANIZER ONLY — 43 named venues
UPDATE fields SET map_visibility = 'organizer_only'
  WHERE name IN ('Boisko Parafialne',
          'Boisko SP2',
          'Boisko do koszykówki',
          'Boisko gminne',
          'Boisko górne - stadion',
          'Boisko przy Zespole Szkolno - Przedszkolnym w Maniewie',
          'Boisko tenis/siatkówka/koszykówka',
          'Boisko w Robakowie',
          'Boisko wielofunkcyjne',
          'Centrum Aktywności Frajda',
          'Centrum Sportowe Remes',
          'Centrum Tenisowe Sobota',
          'Centrum kultury i sportu w Sadach',
          'GKS Golęczewo',
          'GKS Gułtowy',
          'Gameness Team',
          'Klub Sportowy Korona Zakrzewo',
          'Kortowo',
          'Korty Tenisowe',
          'LSS Ptaszkowo',
          'LZS "Zieloni" Gaj Mały',
          'Laba Sport',
          'Liga Obrony Kraju',
          'Luboński 1943 Luboń',
          'Maratończyk Brzeźno',
          'Nowy Stadion Średzki',
          'Orlik (koszykówka)',
          'Orlik 2012 - Boisko do piłki nożnej',
          'Orlik 2012 - boisko do koszykówki',
          'Orlik Białężyn',
          'Orlik Głuchowo',
          'Orlik Skórzewo',
          'POSiR Kiekrz',
          'Plac do ćwiczeń',
          'Przedszkole nr 100 Mali Poznaniacy',
          'Siłownia Słodkiewicz',
          'Spójnia Strykowo',
          'Stadion NKS Niepruszewo',
          'Stadion Patrii Buk',
          'Swarzędzkie Centrum Sportu i Rekreacji');

UPDATE fields SET map_visibility = 'organizer_only'
  WHERE name IN ('UKS Złoci Złotkowo',
          'Zarząd Osiedla Ławica; Urząd Miasta Poznania',
          'stadion K.S. Lipno Stęszew');

-- ────────────────────────────────────────────────────────────
-- BLOCK 2: Generic / ambiguous names — decided by DB data quality
--   Matches rows whose name starts with common prefixes.
--   Visibility is based on DB columns: address / phone / email / website.
-- ────────────────────────────────────────────────────────────

-- Generic names in CSV (used for WHERE name IN below):
--   Boisko Grunwald
--   Boisko Sportowe
--   Boisko sportowe
--   Boisko sportowe na Zielińcu
--   Boisko sportowe · beton
--   Boisko sportowe · mączka ceglana
--   Boisko sportowe · piasek
--   Boisko sportowe · sztuczna trawa
--   Boisko sportowe · tartan / asfalt
--   Boisko sportowe · trawa naturalna
--   Boisko — baseball
--   Boisko — baseball · tartan / asfalt
--   Boisko — hokej
--   Boisko — hokej na trawie
--   Boisko — hokej na trawie · sztuczna trawa
--   Boisko — koszykówka
--   Boisko — koszykówka · beton
--   Boisko — koszykówka · mączka ceglana
--   Boisko — koszykówka · sztuczna trawa
--   Boisko — koszykówka · tartan / asfalt
--   Boisko — koszykówka · trawa naturalna
--   Boisko — piłka nożna
--   Boisko — piłka nożna · beton
--   Boisko — piłka nożna · piasek
--   Boisko — piłka nożna · sztuczna trawa
--   Boisko — piłka nożna · tartan / asfalt
--   Boisko — piłka nożna · trawa naturalna
--   Boisko — piłka ręczna
--   Boisko — piłka ręczna · piasek
--   Boisko — piłka ręczna · sztuczna trawa
--   Boisko — piłka ręczna · tartan / asfalt
--   Boisko — siatkówka
--   Boisko — siatkówka · piasek
--   Boisko — siatkówka · sztuczna trawa
--   Boisko — siatkówka · tartan / asfalt
--   Boisko — siatkówka · trawa naturalna
--   Hala Sportowa, siłownia, sauna

-- Mark as 'public' when DB record has both a proper address AND contact info
UPDATE fields SET map_visibility = 'public'
  WHERE name IN ('Boisko Grunwald', 'Boisko Sportowe', 'Boisko sportowe', 'Boisko sportowe na Zielińcu', 'Boisko sportowe · beton', 'Boisko sportowe · mączka ceglana', 'Boisko sportowe · piasek', 'Boisko sportowe · sztuczna trawa', 'Boisko sportowe · tartan / asfalt', 'Boisko sportowe · trawa naturalna', 'Boisko — baseball', 'Boisko — baseball · tartan / asfalt', 'Boisko — hokej', 'Boisko — hokej na trawie', 'Boisko — hokej na trawie · sztuczna trawa', 'Boisko — koszykówka', 'Boisko — koszykówka · beton', 'Boisko — koszykówka · mączka ceglana', 'Boisko — koszykówka · sztuczna trawa', 'Boisko — koszykówka · tartan / asfalt', 'Boisko — koszykówka · trawa naturalna', 'Boisko — piłka nożna', 'Boisko — piłka nożna · beton', 'Boisko — piłka nożna · piasek', 'Boisko — piłka nożna · sztuczna trawa', 'Boisko — piłka nożna · tartan / asfalt', 'Boisko — piłka nożna · trawa naturalna', 'Boisko — piłka ręczna', 'Boisko — piłka ręczna · piasek', 'Boisko — piłka ręczna · sztuczna trawa', 'Boisko — piłka ręczna · tartan / asfalt', 'Boisko — siatkówka', 'Boisko — siatkówka · piasek', 'Boisko — siatkówka · sztuczna trawa', 'Boisko — siatkówka · tartan / asfalt', 'Boisko — siatkówka · trawa naturalna', 'Hala Sportowa, siłownia, sauna')
  AND address IS NOT NULL
  AND address !~ '^\s*(Pozna[nń])?\s*$'   -- not blank / city-only
  AND position(',' IN address) > 0            -- contains comma = street+number
  AND (
    phone IS NOT NULL
    OR email IS NOT NULL
    OR (website IS NOT NULL AND website NOT LIKE '%orlik2012%')
  );

-- Mark as 'organizer_only' when there is contact but no specific address
UPDATE fields SET map_visibility = 'organizer_only'
  WHERE name IN ('Boisko Grunwald', 'Boisko Sportowe', 'Boisko sportowe', 'Boisko sportowe na Zielińcu', 'Boisko sportowe · beton', 'Boisko sportowe · mączka ceglana', 'Boisko sportowe · piasek', 'Boisko sportowe · sztuczna trawa', 'Boisko sportowe · tartan / asfalt', 'Boisko sportowe · trawa naturalna', 'Boisko — baseball', 'Boisko — baseball · tartan / asfalt', 'Boisko — hokej', 'Boisko — hokej na trawie', 'Boisko — hokej na trawie · sztuczna trawa', 'Boisko — koszykówka', 'Boisko — koszykówka · beton', 'Boisko — koszykówka · mączka ceglana', 'Boisko — koszykówka · sztuczna trawa', 'Boisko — koszykówka · tartan / asfalt', 'Boisko — koszykówka · trawa naturalna', 'Boisko — piłka nożna', 'Boisko — piłka nożna · beton', 'Boisko — piłka nożna · piasek', 'Boisko — piłka nożna · sztuczna trawa', 'Boisko — piłka nożna · tartan / asfalt', 'Boisko — piłka nożna · trawa naturalna', 'Boisko — piłka ręczna', 'Boisko — piłka ręczna · piasek', 'Boisko — piłka ręczna · sztuczna trawa', 'Boisko — piłka ręczna · tartan / asfalt', 'Boisko — siatkówka', 'Boisko — siatkówka · piasek', 'Boisko — siatkówka · sztuczna trawa', 'Boisko — siatkówka · tartan / asfalt', 'Boisko — siatkówka · trawa naturalna', 'Hala Sportowa, siłownia, sauna')
  AND map_visibility <> 'public'               -- don't downgrade what we just promoted
  AND (
    phone IS NOT NULL
    OR email IS NOT NULL
    OR (website IS NOT NULL AND website NOT LIKE '%orlik2012%')
  );

-- Mark remaining generic entries as 'organizer_only' (no address, no contact)
UPDATE fields SET map_visibility = 'organizer_only'
  WHERE name IN ('Boisko Grunwald', 'Boisko Sportowe', 'Boisko sportowe', 'Boisko sportowe na Zielińcu', 'Boisko sportowe · beton', 'Boisko sportowe · mączka ceglana', 'Boisko sportowe · piasek', 'Boisko sportowe · sztuczna trawa', 'Boisko sportowe · tartan / asfalt', 'Boisko sportowe · trawa naturalna', 'Boisko — baseball', 'Boisko — baseball · tartan / asfalt', 'Boisko — hokej', 'Boisko — hokej na trawie', 'Boisko — hokej na trawie · sztuczna trawa', 'Boisko — koszykówka', 'Boisko — koszykówka · beton', 'Boisko — koszykówka · mączka ceglana', 'Boisko — koszykówka · sztuczna trawa', 'Boisko — koszykówka · tartan / asfalt', 'Boisko — koszykówka · trawa naturalna', 'Boisko — piłka nożna', 'Boisko — piłka nożna · beton', 'Boisko — piłka nożna · piasek', 'Boisko — piłka nożna · sztuczna trawa', 'Boisko — piłka nożna · tartan / asfalt', 'Boisko — piłka nożna · trawa naturalna', 'Boisko — piłka ręczna', 'Boisko — piłka ręczna · piasek', 'Boisko — piłka ręczna · sztuczna trawa', 'Boisko — piłka ręczna · tartan / asfalt', 'Boisko — siatkówka', 'Boisko — siatkówka · piasek', 'Boisko — siatkówka · sztuczna trawa', 'Boisko — siatkówka · tartan / asfalt', 'Boisko — siatkówka · trawa naturalna', 'Hala Sportowa, siłownia, sauna')
  AND map_visibility NOT IN ('public', 'organizer_only');

-- ────────────────────────────────────────────────────────────
-- BLOCK 3: Catch-all — everything else → organizer_only
--   Fields not matched above keep their default from migration 024.
--   Run this to explicitly promote any remaining 'organizer_only' → kept,
--   and ensure nothing is accidentally left hidden.
-- ────────────────────────────────────────────────────────────

-- (No hidden entries generated — all unrecognised fields stay organizer_only)

-- Done. Review before running on production.
-- Total named venues processed: 141
-- Total generic name groups: 37
